Array.prototype.each = function (it) {};
Element.prototype.getElementsBySelector = function (s) {};
Element.prototype.morph = function (m) {};
var Ajax = {};
var Hash = {};
Ajax.Request = function(a, b, c) {};
var $ = function (o) {};
var $$ = function (o) {};
var $H = function (o) {};
var localStorage;
var sessionStorage;
var JSON = {};
JSON.parse = function(json) {};
JSON.stringify = function(jsonObj) {};
Object.prototype.reset = function () {};
Object.prototype.name;
Object.prototype.fov;
Object.prototype.scale;
Object.prototype.mX;
Object.prototype.mY;
Object.prototype.mZ;
Object.prototype.mW;
Object.prototype.xyStep;
Object.prototype.xzStep;
Object.prototype.xwStep;
Object.prototype.yzStep;
Object.prototype.ywStep;
Object.prototype.zwStep;
Object.prototype.vertices;
Object.prototype.edges;
Object.prototype.edgesColor;
Object.prototype.lineWidth;
Object.prototype.transition;